name: Android CI

on:

  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master

      - name: Check code quality
        run: ./gradlew thepeer-android:ktlint

      - name: Build thepeer-android library
        run: ./gradlew thepeer-android:build

      - name: Build Kotlin demo
        run: ./gradlew demo-app:build

      - name: Build Java demo
        run: ./gradlew java-demo:build
